/**
 * Selection des photographies du site, par page.
 *
 * Chaque image a ete ouverte et regardee avant d etre cablee (planches-contact
 * de la mediatheque) : le texte de remplacement decrit ce que la photo montre,
 * la legende (cartel) dit ou et quand, sans rien ajouter que le nom du fichier
 * ou le contenu deja publie n atteste.
 *
 * `f`   chemin dans la mediatheque BATIBIG, dossier ATELIER LE BOULLUEC
 * `net` true si la photo ne porte pas le filigrane www.atelierdemenuiserie.fr :
 *       toutes les autres sont recadrees de leur bande droite et de leur pied,
 *       ou le filigrane et le logo se trouvent (le sujet n y est jamais).
 * `grand` true si la photo porte un bandeau ou un hero (variante de 1800 px).
 * `coupe` part de la largeur conservee, quand le logo tombe plus a gauche.
 *
 * Les photos d escaliers du dossier `escaliers` sont des visuels de catalogue
 * du groupement Treppenmeister, pas des chantiers de l atelier : elles sont
 * legendees comme modeles du groupement, et les escaliers reellement poses
 * (Palaiseau, Saclay, Paray-Vieille-Poste, rue de Vaucouleurs) passent devant.
 */
const J = "leboulluec.com/journal-de-chantiers";
const G = "leboulluec.com/galerie-generale";
const B = "leboulluec.com/belles-portes-de-rue";
const E = "leboulluec.com/escaliers";
const A = "atelierdemenuiserie.fr";
const TM = "Modèle du groupement Treppenmeister";

export const PHOTOS = {
  // --- Bandeaux et hero --------------------------------------------------
  "longchamp": { f: `${G}/porte-cochere-111-rue-de-longchamp-reposee-mise-en-peinture.jpg`, grand: true,
    alt: "Porte cochère cintrée à deux vantaux en bois, vitrée de grilles forgées en partie haute, sous le numéro 111",
    leg: "111 rue de Longchamp, Paris 16e · reposée et remise en peinture" },
  "quatre-vantaux": { f: `${J}/a-trier/porte-quatre-vantaux-haussmannienne.jpeg`, net: true, grand: true,
    alt: "Porte intérieure vitrée à quatre vantaux blancs, petits bois et moulures, dans un appartement haussmannien",
    leg: "Porte intérieure à quatre vantaux" },
  "vaucouleurs-apres": { f: `${J}/2021/2021-12-restauration-escalier-rue-vaucouleur-terminee.jpg`, grand: true,
    alt: "Cage d’escalier ancienne vue en plongée, marches de bois neuves épousant le tournant",
    leg: "Rue de Vaucouleurs, Paris · 2021 · après travaux" },
  "verneuil": { f: `${J}/2019/2019-09-grille-sas-54-rue-de-verneuil-paris-7-vue-ensemble.jpg`, grand: true,
    alt: "Grille de sas noire à barreaux et imposte à losanges fermant un porche, cour pavée au fond",
    leg: "54 rue de Verneuil, Paris 7e · 2019" },
  "puits-lumiere": { f: `${J}/a-trier/vitrerie.jpeg`, net: true, grand: true,
    alt: "Dalle de verre encastrée dans un parquet, laissant voir la fenêtre de l’étage inférieur",
    leg: "Vitrage de sol" },
  "mercier-apres": { f: `${J}/2018/2018-09-porte-cochere-12-rue-du-cardinal-mercier-paris-9-apres.jpg`, net: true, grand: true,
    alt: "Porte cochère sombre à deux vantaux sculptés sous une imposte vitrée, encadrée de deux lanternes, après restauration",
    leg: "12 rue du Cardinal-Mercier, Paris 9e · 2018 · après" },
  "porte-rouge": { f: `${J}/a-trier/porte-cochere-refaite-vue-exterieure.png`, net: true, grand: true,
    alt: "Porte cochère rouge cintrée à deux vantaux, portillon et boutons de laiton, sur une façade ocre",
    leg: "Porte cochère refaite, vue extérieure" },
  "medium-atelier": { f: `${J}/2018/2018-05-agencement-en-medium-epais-atelier-1.jpg`, grand: true,
    alt: "Agencement en médium épais monté à blanc dans l’atelier, étagères et caissons, outillage sur l’établi",
    leg: "À l’atelier · agencement en médium épais, 2018" },
  "verriere": { f: `${J}/2021/2021-02-verriere-atelier.jpg`, grand: true, coupe: 0.78,
    alt: "Verrière d’atelier en acier noir et verre fermant une cuisine, sol à damier",
    leg: "Verrière d’atelier · 2021" },
  "chaussee-dantin": { f: `${G}/porte-cochere-monumentale-68-rue-de-la-chaussee-d-antin-en-cours-de-repose.jpg`, net: true, grand: true,
    alt: "Vantail de porte cochère monumentale soulevé au palan sous une imposte en éventail, compagnon au pied",
    leg: "68 rue de la Chaussée-d’Antin, Paris · repose d’un vantail" },
  "des-dames": { f: `${J}/2017/2017-10-porte-batarde-24-rue-des-dames-paris-17-apres-restauration.jpg`, net: true, grand: true,
    alt: "Porte bâtarde en chêne clair à deux vantaux, grilles de fonte dans les panneaux hauts",
    leg: "24 rue des Dames, Paris 17e · 2017 · après restauration" },

  // --- L’atelier ----------------------------------------------------------
  "bonvin": { f: `${J}/2022/2022-08-porte-34-rue-francois-bonvin-faconnage-atelier.jpg`,
    alt: "Porte à deux vantaux en chêne nu, vitrée en partie haute, debout dans l’atelier de Massy avant finition",
    leg: "34 rue François-Bonvin, Paris · 2022 · à l’atelier" },
  "richer": { f: `${J}/2022/2022-04-2-rue-richer-en-cours-de-repose-apres-faconnage.jpg`,
    alt: "Compagnon penché, aspirateur en main, au pied d’une porte d’immeuble en cours de repose",
    leg: "2 rue Richer, Paris 9e · 2022 · repose après façonnage" },
  "las-cases": { f: `${J}/2023/2023-03-porte-13-rue-las-cases-detail-atelier-2.jpg`,
    alt: "Vue plongeante de l’atelier : vantaux de chêne sur tréteaux, épure agrafée sur le panneau, compagnon au sol",
    leg: "13 rue Las Cases, Paris 7e · 2023 · à l’atelier" },
  "marquise-st-honore": { f: `${J}/2020/2020-07-marquise-rue-st-honore-en-atelier.jpg`,
    alt: "Ossature d’acier d’une marquise en cours d’assemblage, posée sur les tréteaux de l’atelier",
    leg: "Marquise, rue Saint-Honoré · 2020 · à l’atelier" },
  "marquise-duvernet": { f: `${J}/2021/2021-08-marquise-14-rue-moutin-duvernet-en-atelier.jpg`,
    alt: "Marquise en fer forgé à volutes posée sur le sol de l’atelier, son ombre portée au sol",
    leg: "14 rue Mouton-Duvernet, Paris 14e · 2021 · à l’atelier" },
  "saint-paul": { f: `${J}/2020/2020-05-grille-sas-10-rue-saint-paul-paris-4-atelier.jpg`,
    alt: "Cadre de grille de sas en acier brut soudé, à plat sur les tréteaux de l’atelier",
    leg: "10 rue Saint-Paul, Paris 4e · 2020 · à l’atelier" },
  "meulage": { f: `${A}/a-trier/atelierdemenuiserie.jpg`, net: true,
    alt: "Compagnon meulant un profilé d’acier sur un établi de l’atelier, gerbe d’étincelles",
    leg: "Le travail du métal, à l’atelier" },
  "lappe-atelier": { f: `${J}/2025/2025-03---14-rue-de-lappe---p3-travaux-atelier.jpg`,
    alt: "Vantail posé à plat sur les établis, oculus et moulures déposés pour restauration",
    leg: "14 rue de Lappe, Paris 11e · 2025 · à l’atelier" },
  "garde-corps-atelier": { f: `${A}/amenagements-exterieurs/2.jpg`, net: true,
    alt: "Sections de garde-corps en bois assemblées et serrées sur les établis de l’atelier",
    leg: "Garde-corps en bois, au façonnage" },
  "chassis-atelier": { f: `${G}/oculus-ouvrant-3---paumelles.jpg`, net: true,
    alt: "Châssis de chêne en cours de façonnage, paumelles posées, vitrage encore sous film protecteur",
    leg: "Châssis vitré, à l’atelier" },
  "grille-faconnage": { f: `${J}/a-trier/faconnage-grille-sur-mesure.jpeg`, net: true,
    alt: "Grille à volutes serrée sur un établi, perceuse en main, pendant son façonnage",
    leg: "Façonnage d’une grille sur mesure" },

  // --- Portes cochères et portes ------------------------------------------
  "mercier-avant": { f: `${J}/2018/2018-09-porte-cochere-12-rue-du-cardinal-mercier-paris-9-avant.jpg`, net: true,
    alt: "Porte cochère à deux vantaux sculptés, teinte grisée et ferrures encrassées, avant travaux",
    leg: "12 rue du Cardinal-Mercier · 2018 · avant" },
  "mercier-cours-1": { f: `${J}/2018/2018-09-porte-cochere-12-rue-du-cardinal-mercier-paris-9-travaux-cours-1.jpg`, net: true,
    alt: "La même porte décapée : chêne nu, mascarons et grilles dégagés",
    leg: "12 rue du Cardinal-Mercier · décapage" },
  "mercier-detail": { f: `${J}/2018/2018-09-porte-cochere-12-rue-du-cardinal-mercier-paris-9-detail-1.jpg`, net: true,
    alt: "Penture forgée en fleuron clouée sur un panneau de chêne",
    leg: "12 rue du Cardinal-Mercier · penture forgée" },
  "conde-avant": { f: `${J}/2025/2025-05-16-rue-de-conde-avant-restauration-sur-place-1.jpg`,
    alt: "Porte cochère bleue dont le pied des vantaux est entaillé, chantier ouvert sur bâche",
    leg: "16 rue de Condé · 2025 · restauration sur place" },
  "conde-greffe": { f: `${J}/2025/2025-05-16-rue-de-conde-avant-restauration-sur-place-2.jpg`,
    alt: "Bas de vantail bleu recevant une pièce de chêne neuve, outillage électroportatif au sol",
    leg: "16 rue de Condé · la greffe posée" },
  "conde-apres": { f: `${J}/2025/2025-05-16-rue-de-conde-apres-restauration-avant-peinture-1.jpg`,
    alt: "Pied de porte cochère bleue avec traverse basse neuve en sous-couche, sur le pavé",
    leg: "16 rue de Condé · traverse basse neuve, avant peinture" },
  "ija-avant": { f: `${J}/2023/2023-07-porte-acier-institut-des-jeunes-aveugles-paris-7-avant-restauration.jpg`,
    alt: "Porte d’acier cintrée dans un mur d’enduit, peinture bleue écaillée et rouille",
    leg: "Institut des Jeunes Aveugles, Paris 7e · 2023 · avant" },
  "ija-apres": { f: `${J}/2023/2023-07-porte-acier-institut-des-jeunes-aveugles-paris-7-apres-restauration-ext.jpg`,
    alt: "La même porte d’acier cintrée, relaquée en bleu",
    leg: "Institut des Jeunes Aveugles · après remise en peinture" },
  "abbesses-avant": { f: `${J}/2021/2021-01-porte-cochere-40-rue-des-abbesses-avant-restauration-int.jpg`,
    alt: "Porte cochère vue du porche avant travaux, vantail doublé d’un panneau brut, imposte en fer forgé",
    leg: "40 rue des Abbesses · 2021 · avant, vue intérieure" },
  "abbesses-apres": { f: `${J}/2021/2021-01-porte-cochere-40-rue-des-abbesses-apres-restauration-int.jpg`,
    alt: "La même porte vue du porche après restauration, vantaux vernis couleur miel",
    leg: "40 rue des Abbesses · après, vue intérieure" },
  "perle-avant": { f: `${J}/2022/2022-09-porte-cochere-3-rue-de-la-perle-avant-remplacement-int-detail.jpg`,
    alt: "Pied de vantail ancien, bois gris fendu et délavé, au ras du seuil de pierre",
    leg: "3 rue de la Perle · 2022 · avant remplacement" },
  "perle-apres": { f: `${J}/2022/2022-09-porte-cochere-3-rue-de-la-perle-apres-faconnage-vue-ext.jpg`,
    alt: "Porte cochère neuve peinte en vert, deux vantaux à panneaux et heurtoirs, sous un mascaron",
    leg: "3 rue de la Perle · porte neuve posée" },
  "lemoine": { f: `${J}/2019/2019-12-porte-cochere-42-rue-du-cardinal-lemoine-paris-5-vue-ensemble.jpg`,
    alt: "Porte cochère en chêne vernis à deux vantaux, numéro 42, encadrée de chasse-roues en fonte",
    leg: "42 rue du Cardinal-Lemoine, Paris 5e · 2019" },
  "washington": { f: `${J}/2024/2024-01-grille-de-defense-32-rue-de-washington-detail.jpg`,
    alt: "Fenêtre à petits carreaux protégée par une grille de défense à barreaux, façade en pierre de taille",
    leg: "32 rue de Washington, Paris · 2024" },
  "boulard": { f: `${J}/2020/2020-03-facade-acier-arc-surbaisse-41-rue-boulard-paris-14.jpg`,
    alt: "Châssis en acier noir à arcs surbaissés, vitrés, dans une cour ancienne",
    leg: "41 rue Boulard, Paris 14e · 2020" },
  "motte-modele": { f: `${J}/2025/2025-01-porte-sas-9-avenue-de-la-motte-piquet-dessin-modele.jpg`,
    alt: "Porte de sas en acier à barreaux et verre imprimé, relevée comme modèle avant façonnage",
    leg: "9 avenue de La Motte-Picquet · 2025 · l’ouvrage modèle" },
  "corbeillier": { f: `${J}/2013/2013-02-porte-sur-rue-corbeillier-3-tiercee-chene-avec-grilles.jpg`,
    alt: "Porte tiercée en chêne clair à deux grilles ouvragées, sur une façade rose",
    leg: "Porte tiercée en chêne à grilles · 2013" },
  "paul-lelong-avant": { f: `${J}/2024/2024-02---porte-cochere-7-rue-paul-lelong-paris-2-photo-1-avant-restauration-.jpg`,
    alt: "Porte cochère vert sombre sous un arc plein cintre à imposte en éventail, avant travaux",
    leg: "7 rue Paul-Lelong, Paris 2e · 2024 · avant" },
  "paul-lelong-apres": { f: `${J}/2024/2024-02---porte-cochere-7-rue-paul-lelong-paris-2-photo-2-apres-restauration-.jpg`,
    alt: "La même porte cochère restaurée et repeinte en bleu pétrole",
    leg: "7 rue Paul-Lelong · après restauration" },
  "vieille-du-temple": { f: `${J}/2021/2021-12-porte-cochère-44-rue-vieille-du-temple-p4-après-restauration-2803958b.jpg`,
    alt: "Porte cochère bleue sous un arc à mascaron, après restauration",
    leg: "44 rue Vieille-du-Temple, Paris 4e · 2021" },
  "chauveau-lagarde": { f: `${J}/2020/2020-01-porte-cochère-4-rue-chauveau-lagarde-paris-8---p06---vue-ext-générale.jpg`,
    alt: "Porte cochère gris-vert à grilles ouvragées, entre deux pilastres de pierre",
    leg: "4 rue Chauveau-Lagarde, Paris 8e · 2020" },
  "dechargeurs": { f: `${J}/2020/2020-06-porte-cochère-9-rue-des-déchargeurs-paris-1-photo-1-vue-ext.jpg`,
    alt: "Porte cochère vert-de-gris à heurtoir, sous un encadrement de pierre sculpté",
    leg: "9 rue des Déchargeurs, Paris 1er · 2020" },
  "grevin": { f: `${J}/2017/2017-01-porte-cochère-musée-grevin-après-restauration.jpg`,
    alt: "Porte rouge à grilles du Cabinet fantastique du musée Grévin, sous une enseigne peinte",
    leg: "Musée Grévin, Paris 9e · 2017 · après restauration" },
  "lappe-apres": { f: `${J}/2025/2025-03---14-rue-de-lappe---p5-vue-ext.jpg`,
    alt: "Porte cochère bleu nuit dans un encadrement de pierre sculpté, fleurs en façade",
    leg: "14 rue de Lappe · après repose" },
  "saint-sulpice": { f: `${J}/2024/2024-04---6-place-saint-sulpice-p1.jpg`,
    alt: "Porte cochère bleue à médaillon sculpté, portillon ouvert sur le porche",
    leg: "6 place Saint-Sulpice, Paris 6e · 2024" },
  "arcade": { f: `${J}/2023/2023-01---porte-cochere-4-rue-de-l-arcade-ext-.jpg`,
    alt: "Porte cochère bleue à grilles sous une imposte ajourée, entre deux devantures",
    leg: "4 rue de l’Arcade, Paris 8e · 2023" },
  "montparnasse": { f: `${J}/2016/2016-01-porte-chene-restaurée-bd-montparnasse-paris.jpg`, net: true,
    alt: "Porte d’immeuble à deux vantaux en chêne foncé, panneaux sculptés et grilles en fonte",
    leg: "Boulevard du Montparnasse, Paris · 2016 · restaurée" },
  "remploi-grille": { f: `${J}/2015/2015-01-porte-chene-grille-ancienne-109-rue-du-dessous-des-berges-atelier.jpg`, net: true,
    alt: "Vantail en chêne clair posé sur l’établi, autour d’une grille ancienne en fer forgé remployée",
    leg: "Rue du Dessous-des-Berges · 2015 · remploi d’une grille ancienne" },
  "porte-grille-neuve": { f: `${J}/2015/2015-04-porte-en-chêne-avec-grille-neuve.jpg`, net: true,
    alt: "Porte de pavillon en chêne vitrée d’une grille neuve, sous une marquise, façade de brique",
    leg: "Porte en chêne et grille neuve · 2015" },
  "sas-huissiers": { f: `${J}/2016/2016-09-porte-sas-chene-2-rue-des-huissiers-neuilly-vue-ensemble.jpg`, net: true,
    alt: "Porte de sas vitrée à petits bois en chêne, dans le hall d’un immeuble",
    leg: "2 rue des Huissiers, Neuilly · 2016" },
  "porte-rome": { f: `${J}/2016/2016-11-porte-chêne-129-rue-de-rome.jpg`, net: true,
    alt: "Porte pleine en chêne vernis à panneaux, surmontée d’une imposte vitrée",
    leg: "129 rue de Rome, Paris · 2016" },

  // --- Agencement, mobilier, extérieurs -----------------------------------
  "placard-moulures": { f: `${G}/placard-haussmannien-fermine-moulures-en-applique-p1.jpg`,
    alt: "Placard à trois portes ornées de moulures en applique, dans une chambre à parquet point de Hongrie",
    leg: "Placard à moulures en applique" },
  "bibliotheque-cheminee": { f: `${G}/bibliotheque-en-chene.jpeg`, net: true,
    alt: "Bibliothèque en chêne montée de part et d’autre d’une cheminée, avec logement pour téléviseur",
    leg: "Bibliothèque en chêne autour d’une cheminée" },
  "lamelle-chene": { f: `${J}/2017/2017-12-agencement-en-lamellé-chêne---vue-d-ensemble-1.jpg`, net: true,
    alt: "Bibliothèque en lamellé de chêne encadrant une cheminée, pièce encore vide",
    leg: "Agencement en lamellé de chêne · 2017" },
  "dressing": { f: `${G}/agencement-placard.jpg`,
    alt: "Intérieur d’un dressing : étagères, penderie et paniers coulissants",
    leg: "Aménagement intérieur de dressing" },
  "sous-pente": { f: `${G}/rangement-agencé-sous-pente-colombier-1.jpg`, net: true,
    alt: "Rangements blancs épousant une sous-pente, avec plan de bureau en retour",
    leg: "Rangements sous pente" },
  "banque-hotel": { f: `${J}/2018/2018-02-banque-d-accueil-hotel.jpg`, net: true,
    alt: "Banque d’accueil laquée noire à bandeau doré, dans le hall d’un hôtel",
    leg: "Banque d’accueil d’hôtel · 2018" },
  "bibliotheque-plaquee": { f: `${G}/meuble-salon-verni.jpg`,
    alt: "Bibliothèque en panneaux plaqués chêne clair, casiers ouverts et portes basses",
    leg: "Bibliothèque plaquée chêne" },
  "bureau-chene": { f: `${A}/mobilier/2-1.jpg`, net: true,
    alt: "Long bureau en lames de chêne posé sur quatre caissons ouverts, sous une fenêtre",
    leg: "Ensemble bureau en chêne massif" },
  "rayonnages-boutique": { f: `${G}/etageres-medium-epais-magasin-remplies.jpeg`, net: true,
    alt: "Rayonnages en médium épais garnis de produits dans une boutique d’épicerie",
    leg: "Rayonnages de boutique" },
  "rampe-pmr": { f: `${A}/amenagements-exterieurs/5.jpg`, net: true,
    alt: "Rampe d’accès en lames de bois bordée d’une main courante en acier laqué blanc",
    leg: "Rampe d’accès, lames de bois" },
  "abri-poubelles": { f: `${J}/2020/2020-07-abri-poubelles-en-iroko-posée.jpg`,
    alt: "Coffre à conteneurs en lames d’iroko posé sous un porche d’immeuble",
    leg: "Abri à conteneurs en iroko · 2020" },
  "abri-fumeurs": { f: `${G}/abris-fumeurs-clinique-fauvettes-posé.jpg`,
    alt: "Abri en bois couvert d’une toiture translucide, banc vert à l’intérieur, dans un parc",
    leg: "Abri extérieur, clinique des Fauvettes" },
  "garde-corps-sceaux": { f: `${J}/2015/2015-02-garde-corps-pavillon-à-sceaux.jpg`, net: true,
    alt: "Garde-corps en bois en cours de pose depuis un échafaudage, devant une lucarne",
    leg: "Pose d’un garde-corps, Sceaux · 2015" },
  "pergola": { f: `${J}/2015/2015-11-pergola-acier-et-mélèze-jardin-de-ville-paris-14.jpg`, net: true,
    alt: "Pergola en acier doublée d’un claustra en mélèze, dans un jardin de ville planté",
    leg: "Pergola acier et mélèze, Paris 14e · 2015" },
  "garde-corps-verre": { f: `${G}/garde-corps-bois-et-verre-photo1.jpg`, net: true,
    alt: "Garde-corps en bois et verre sur le balcon d’une maison à bardage de bois",
    leg: "Garde-corps bois et verre" },

  // --- Escaliers réellement posés -----------------------------------------
  "palaiseau": { f: `${J}/2023/2023-08---escalier-palaiseau-4.jpg`,
    alt: "Escalier droit à marches de bois clair sur limon acier noir, garde-corps en verre",
    leg: "Palaiseau · 2023 · escalier à limon acier" },
  "palaiseau-pose": { f: `${J}/2023/2023-08---escalier-palaiseau-1.jpg`,
    alt: "Limon acier en crémaillère posé contre le mur, premières marches de bois en place",
    leg: "Palaiseau · 2023 · la pose du limon" },
  "saclay": { f: `${J}/2023/2023-12-escalier-saclay-apres-remplacement-2.jpg`,
    alt: "Escalier tournant à marches de bois clair et limon acier noir, garde-corps à câbles",
    leg: "Saclay · 2023 · escalier remplacé" },
  "paray-apres": { f: `${J}/2023/2023-10-escalier-paray-vieille-poste-apres-travaux-2.jpg`,
    alt: "Escalier à marches de bois ouvertes montant le long d’un mur, garde-corps à câbles tendus",
    leg: "Paray-Vieille-Poste · 2023 · après travaux" },
  "paray-pendant": { f: `${J}/2023/2023-10-escalier-paray-vieille-poste-pendant-travaux.jpg`,
    alt: "Escalier en cours de pose, escabeau et cartons de marches au pied",
    leg: "Paray-Vieille-Poste · 2023 · pendant les travaux" },
  "main-courante": { f: `${J}/2023/2023-03---main-courante-debillardee-photo1.jpg`,
    alt: "Main courante en bois débillardée suivant la courbe d’un escalier à balustres",
    leg: "Main courante débillardée · 2023" },
  "vaucouleurs-avant": { f: `${J}/2021/2021-12-restauration-escalier-rue-vaucouleur-avant-travaux.jpg`,
    alt: "Escalier ancien aux marches peintes en vert, usées et écaillées, avant travaux",
    leg: "Rue de Vaucouleurs · 2021 · avant" },
  "vaucouleurs-cours": { f: `${J}/2021/2021-12-restauration-escalier-rue-vaucouleur-en-cours.jpg`,
    alt: "Le même escalier en cours de reprise : marches déposées une à une, volée restant praticable",
    leg: "Rue de Vaucouleurs · 2021 · en cours" },
  "escalier-chene-2017": { f: `${J}/2017/2017-06-retauration-escalier-en-chêne.jpg`, net: true,
    alt: "Escalier ancien en chêne dans une maison, marches et contremarches reprises",
    leg: "Escalier en chêne restauré · 2017" },

  // --- Modèles Treppenmeister (catalogue du groupement) -------------------
  "tm-suspendu-1": { f: `${E}/escalier-autoporteur-photo-1.jpg`, net: true,
    alt: "Marches de bois clair en porte-à-faux le long d’un mur, garde-corps en verre, séjour ouvert", leg: TM },
  "tm-suspendu-2": { f: `${E}/escalier-autoporteur-photo-5.jpg`, net: true,
    alt: "Marches claires en porte-à-faux devant un parement de pierre, sans limon apparent", leg: TM },
  "tm-suspendu-3": { f: `${E}/escalier-autoporteur-photo-17.jpg`, net: true,
    alt: "Marches en bois suspendues montant vers une mezzanine, garde-corps en verre", leg: TM },
  "tm-colimacon-1": { f: `${E}/escalier-en-colimaçon-photo-2.jpg`, net: true,
    alt: "Escalier hélicoïdal en bois à balustres inox, devant une fenêtre à petits carreaux", leg: TM },
  "tm-colimacon-2": { f: `${E}/escalier-en-colimaçon-photo-5.jpg`, net: true,
    alt: "Vue plongeante sur un escalier hélicoïdal en bois à garde-corps courbe", leg: TM },
  "tm-colimacon-3": { f: `${E}/escalier-en-colimaçon-photo-1.jpg`, net: true,
    alt: "Escalier hélicoïdal en acier gris à barreaudage, vu depuis l’étage", leg: TM },
  "tm-limon-1": { f: `${E}/escalier-à-limon-acier-gamme-ferro-photo-2.jpg`, net: true,
    alt: "Escalier à limon acier gris, marches et main courante en bois, dans un séjour", leg: "Gamme Ferro, groupement Treppenmeister" },
  "tm-limon-2": { f: `${E}/escalier-à-limon-acier-gamme-loft-photo-2.jpg`, net: true,
    alt: "Escalier à double limon acier noir, marches en bois, garde-corps à câbles et verre", leg: "Gamme Loft, groupement Treppenmeister" },
  "tm-garde-corps": { f: `${E}/escalier-à-limon-acier-gamme-loft-photo-9.jpg`, net: true,
    alt: "Escalier à marches blanches et garde-corps en verre à potelets inox, intérieur clair", leg: "Gamme Loft, groupement Treppenmeister" },
  "tm-autoporteur": { f: `${E}/escalier-suspendu-photo-9-3f083524.jpg`, net: true,
    alt: "Escalier en bois quart tournant à balustres inox desservant une mezzanine", leg: TM },

  // --- Serrurerie ---------------------------------------------------------
  "washington-ensemble": { f: `${J}/2024/2024-01-grille-de-defense-32-rue-de-washington-ensemble.jpg`,
    alt: "Deux fenêtres équipées de grilles de défense sur une façade en pierre de taille, lanterne murale",
    leg: "32 rue de Washington, Paris 8e · 2024 · grilles de défense" },
  "grille-atelier": { f: `${J}/a-trier/grille.jpg`, net: true,
    alt: "Grille en fer forgé à volutes posée à plat sur une porte vitrée, à l’atelier",
    leg: "Grille en fer forgé, à l’atelier" },
  "verneuil-lances": { f: `${J}/2019/2019-09-grille-sas-54-rue-de-verneuil-paris-7-detail-fers-de-lances.jpg`,
    alt: "Fers de lance et imposte à losanges d’une grille de sas, vus en contre-plongée sous une rosace",
    leg: "54 rue de Verneuil · fers de lance" },
  "interphone": { f: `${J}/2020/2020-05-grille-sas-10-rue-saint-paul-paris-4-detail-interphone-intratone.jpg`,
    alt: "Platine d’interphone à clavier montée à côté du montant d’une grille de sas en acier",
    leg: "10 rue Saint-Paul, Paris 4e · 2020 · contrôle d’accès" },
  "pontoise": { f: `${J}/2021/2021-09-motorisation-porte-acier-forge-1-rue-de-pontoise-vue-ensemble-1.jpg`,
    alt: "Porte en acier forgé à volutes sous un porche, bras de motorisation en imposte",
    leg: "1 rue de Pontoise, Paris · 2021 · motorisation" },
  "verin": { f: `${J}/a-trier/motorisation-par-verin-encastre.jpg`, net: true,
    alt: "Vantail en acier laqué noir commandé par un vérin, bandes jaunes et noires au sol",
    leg: "Motorisation par vérin" },
  "bras-compas": { f: `${J}/a-trier/motorisation-par-bras-compas.jpg`, net: true,
    alt: "Bras à compas de motorisation fixé en imposte sur une porte cochère en chêne",
    leg: "Motorisation par bras à compas" },
  "grille-motorisee": { f: `${J}/2013/2013-10-grille-motorisée.jpg`, net: true,
    alt: "Grille barreaudée à deux vantaux fermant un porche pavé",
    leg: "Grille motorisée · 2013" },
  "garniture-laiton": { f: `${G}/serrure.jpeg`, net: true,
    alt: "Poignée et plaque de propreté en laiton montées sur une porte en acajou",
    leg: "Garniture en laiton sur porte ancienne" },
  "bequille-laiton": { f: `${A}/autres-activites/2-3.jpg`, net: true,
    alt: "Béquille en laiton montée sur un montant métallique gris, vue rapprochée",
    leg: "Béquille en laiton" },

  // --- Vitrerie -----------------------------------------------------------
  "porte-vitree": { f: `${A}/vitrerie/porte_inte_rieure_moulure_e_2_6.jpg`, net: true,
    alt: "Porte intérieure vitrée blanche à petits bois, ouverte sur un parquet à bâtons rompus",
    leg: "Porte intérieure vitrée" },
  "verres-biseautes": { f: `${G}/porte-vitrée-à-verres-biseautés-1.jpg`, net: true,
    alt: "Porte à verres biseautés, béquille et entrée de clé en laiton",
    leg: "Verres biseautés" },
  "cloison-acier": { f: `${G}/cloison-acier-et-verre.jpg`,
    alt: "Cloison en acier et verre montée en angle au-dessus d’un plan de travail en bois",
    leg: "Cloison acier et verre" },
  "pare-douche": { f: `${J}/2021/2021-07-pare-douche-et-fenetre-intérieure-acier.jpg`, coupe: 0.78,
    alt: "Paroi de douche en acier noir et verre dans une salle d’eau à carreaux de ciment",
    leg: "Pare-douche en acier · 2021" },
  "cloison-depolie": { f: `${J}/2020/2020-09-cloison-séparative-en-verre-.jpg`,
    alt: "Cloison séparative en verre dépoli montée sur une terrasse",
    leg: "Cloison séparative en verre · 2020" },
  "vitrage-protection": { f: `${J}/a-trier/vitrage-de-protection-sur-mesure.jpg`, net: true,
    alt: "Vitrage de protection posé devant une fenêtre de rez-de-chaussée, façade en pierre",
    leg: "Vitrage de protection sur mesure" },
  "facade-miroir": { f: `${J}/a-trier/facade-miroir-toute-hauteur.jpg`, net: true,
    alt: "Façade de placard toute hauteur habillée de miroir, reflétant l’entrée",
    leg: "Façade de placard en miroir" },
  "salle-de-bain": { f: `${A}/autres-activites/vitrerie.jpg`, net: true,
    alt: "Salle de bain à cloison vitrée et miroirs muraux, sèche-serviettes au premier plan",
    leg: "Vitrerie et miroiterie" },
  "porte-pavillon": { f: `${A}/autres-activites/portes-fenetres.jpg`, net: true,
    alt: "Porte d’entrée de pavillon en chêne à grille ouvragée et vitrage, entre deux rampes",
    leg: "Porte d’entrée vitrée à grille" },
  "marquise-cour": { f: `${J}/2025/2025-01---marquise-sur-porte-cour.jpg`,
    alt: "Marquise en acier et verre déployée en éventail au-dessus d’une porte de cour",
    leg: "Marquise sur porte de cour · 2025" },
  "marquise-lanternes": { f: `${J}/2014/2014-11-marquise-acier-sur-porte-immeuble-hausmannien-paris-8.jpg`, net: true,
    alt: "Marquise en acier et verre au-dessus d’une porte d’immeuble, encadrée de deux lanternes",
    leg: "Marquise et lanternes, Paris 8e · 2014" },

  // --- Belles portes vues sur Paris (relevés de rue, pas des chantiers) ----
  "bp-vintimille": { f: `${B}/porte-batarde-17-rue-de-vintimille-c990059d.jpg`,
    alt: "Porte bâtarde verte cintrée à deux vantaux, dans un encadrement de pierre", leg: "Porte bâtarde · 17 rue de Vintimille, Paris 9e" },
  "bp-bourse": { f: `${B}/porte-batarde-2-place-de-la-bourse-paris-2-3abf81b8.jpg`,
    alt: "Porte bâtarde bleue cintrée à imposte grillagée, façade de pierre", leg: "Porte bâtarde · 2 place de la Bourse, Paris 2e" },
  "bp-sainte-anne": { f: `${B}/porte-batarde-46-rue-saint-anne-paris-2.jpg`,
    alt: "Porte bâtarde en bois sombre à panneaux moulurés, sous une imposte", leg: "Porte bâtarde · 46 rue Sainte-Anne, Paris 2e" },
  "bp-tournelles": { f: `${B}/porte-charretiere-33-rue-des-tournelles-paris-4-face-exterieure-bf7ed908.jpg`,
    alt: "Porte charretière vert sombre cintrée au pied d’une façade de pierre", leg: "Porte charretière · 33 rue des Tournelles, Paris 4e" },
  "bp-sourdiere": { f: `${B}/porte-pietonne-18-rue-de-la-sourdiere-paris-2.jpg`,
    alt: "Porte piétonne rouge à panneaux moulurés, dans un encadrement de pierre", leg: "Porte piétonne · 18 rue de la Sourdière, Paris 2e" },
  "bp-chateau-eau": { f: `${B}/porte-grille-acier---25-rue-du-chateau-d-eau-paris-10-a9453b88.jpg`,
    alt: "Porte cintrée en grille d’acier laissant voir le porche, façade claire", leg: "Porte grille en acier · 25 rue du Château-d’Eau, Paris 10e" },
  "bp-seguier": { f: `${B}/porte-cochere-fin-17eme---46-rue-seguier-paris-6-c0b7671b.jpg`,
    alt: "Porte cochère cintrée en chêne à grands panneaux, fin du XVIIe siècle", leg: "Porte cochère fin XVIIe · 46 rue Séguier, Paris 6e" },
  "bp-amsterdam": { f: `${B}/porte-cochère-empire---80-rue-d-amsterdam-paris-9-91c1de5e.jpg`,
    alt: "Porte cochère bleu sombre de style Empire à panneaux ajourés, dans un encadrement de pierre sculpté", leg: "Porte cochère Empire · 80 rue d’Amsterdam, Paris 9e" },
  "bp-faubourg": { f: `${B}/porte-cochère-monumentale---41-rue-du-faubourg-st-honore-paris-8-a041c42c.jpg`,
    alt: "Porte cochère monumentale verte au fond d’un portail de pierre à fronton", leg: "Porte cochère monumentale · 41 rue du Faubourg-Saint-Honoré, Paris 8e" },
  "bp-la-fontaine": { f: `${B}/porte-sas-art-nouveau---14-rue-de-lafontaine-paris-16-porte-sas-837e1ddb.jpg`,
    alt: "Porte de sas Art nouveau en fer et verre, vue depuis le porche d’un immeuble", leg: "Porte de sas Art nouveau · 14 rue La Fontaine, Paris 16e" },
  "bp-amiral": { f: `${B}/porte-cochère-verre-bois-acier---19-rue-amiral-d-estaing-paris-16-42cb7f52.jpg`,
    alt: "Porte cochère vert sombre à panneaux carrés, sous une baie cintrée vitrée", leg: "Porte cochère verre, bois et acier · 19 rue de l’Amiral-d’Estaing, Paris 16e" },
  "bp-vrilliere": { f: `${B}/porte-cochere-1-rue-de-la-vrilliere-paris-1er.jpg`,
    alt: "Porte cochère bleu nuit cintrée sous un grand arc de pierre sculpté", leg: "1 rue de la Vrillière, Paris 1er" },
  "bp-richelieu": { f: `${B}/porte-cochere-106-rue-de-richelieu-paris-2.jpg`,
    alt: "Porte cochère bleue cintrée à imposte grillagée en éventail", leg: "106 rue de Richelieu, Paris 2e" },
  "bp-messine": { f: `${B}/porte-cochere-14-avenue-de-messine-paris-8.jpg`,
    alt: "Porte cochère en bois ciré à panneaux sculptés, encadrement de pierre", leg: "14 avenue de Messine, Paris 8e" },
  "bp-bingen": { f: `${B}/porte-cochere-15-rue-jacques-bingen-paris-17.jpg`,
    alt: "Porte cochère cintrée en bois naturel à panneaux moulurés", leg: "15 rue Jacques-Bingen, Paris 17e" },
  "bp-messine-16": { f: `${B}/porte-cochere-16-avenue-de-messine-paris-8.jpg`,
    alt: "Porte cochère cintrée en bois vernis sous une façade ornée", leg: "16 avenue de Messine, Paris 8e" },
  "bp-quai-bourbon": { f: `${B}/porte-cochere-29-quai-de-bourbon.jpg`,
    alt: "Porte cochère gris-vert à panneaux sculptés, sous un cartouche de pierre", leg: "29 quai de Bourbon, Paris 4e" },
  "bp-fbg-montmartre": { f: `${B}/porte-cochere-21-rue-du-fbg-montmartre-paris.jpg`,
    alt: "Grande porte cochère cintrée en bois sculpté, deux vantaux ornés", leg: "21 rue du Faubourg-Montmartre, Paris" },
  "bp-galilee": { f: `${B}/porte-cochere-27-rue-galilee-paris-8.jpg`,
    alt: "Porte cochère en bois naturel à panneaux sculptés, encadrée de pierre", leg: "27 rue Galilée, Paris 8e" },
  "bp-bonaparte-28": { f: `${B}/porte-cochere-28-rue-bonaparte-paris-6-.jpg`,
    alt: "Porte cochère vert sombre cintrée, dans une façade de pierre", leg: "28 rue Bonaparte, Paris 6e" },
  "bp-saint-lazare": { f: `${B}/porte-cochere-67-rue-saint-lazare-paris-9.jpg`,
    alt: "Porte cochère cintrée en bois richement sculpté, deux vantaux ornés de médaillons", leg: "67 rue Saint-Lazare, Paris 9e" },
  "bp-lancry": { f: `${B}/porte-cochere-63-rue-de-lancry-paris-10.jpg`,
    alt: "Porte cochère cintrée en bois sculpté sous un décor de pierre", leg: "63 rue de Lancry, Paris 10e" },
  "bp-bonaparte-74": { f: `${B}/porte-cochere-74-rue-bonaparte-paris-6.jpg`,
    alt: "Porte cochère cintrée en chêne sombre à panneaux ornés, sous une grande arcade", leg: "74 rue Bonaparte, Paris 6e" },
  "bp-chateau-eau-36": { f: `${B}/porte-cochère-empire--36-rue-du-chateau-d-eau-2-paris-10-10a76980.jpg`,
    alt: "Porte cochère bleue de style Empire, à panneaux cloutés", leg: "Empire · 36 rue du Château-d’Eau, Paris 10e" },
  "bp-saint-antoine": { f: `${B}/porte-cochère-louis-xiii---21-rue-saint-antoine-paris-4-51298e81.jpg`,
    alt: "Porte cochère rouge Louis XIII cintrée, sous une façade de pierre", leg: "Louis XIII · 21 rue Saint-Antoine, Paris 4e" },
  "bp-lions": { f: `${B}/porte-cochère-louis-xiii---5-rue-des-lions-saint-paul-paris-4-d4463a00.jpg`,
    alt: "Porte cochère rouge Louis XIII sous un arc de pierre, façade du Marais", leg: "Louis XIII · 5 rue des Lions-Saint-Paul, Paris 4e" },
  "bp-phalsbourg": { f: `${B}/porte-cochère-louis-xv---13-rue-de-phalsbourg-paris-8-bb6c3342.jpg`,
    alt: "Porte cochère Louis XV en bois naturel à panneaux chantournés", leg: "Louis XV · 13 rue de Phalsbourg, Paris 8e" },
  "bp-vignon": { f: `${B}/porte-cochère-louis-xv---34-rue-vignon-paris-9-c684bd83.jpg`,
    alt: "Porte cochère Louis XV en chêne à panneaux sculptés et petites grilles", leg: "Louis XV · 34 rue Vignon, Paris 9e" },
  "bp-thorigny": { f: `${B}/porte-cochère-louis-xiii---8-rue-de-thorigny-paris-3--448db121.jpg`,
    alt: "Porte cochère Louis XIII bleu nuit à panneaux sculptés, sous un arc de pierre", leg: "Louis XIII · 8 rue de Thorigny, Paris 3e" },
};

/** Galeries et rangées : suites d’identifiants de PHOTOS. */
export const GALERIES = {
  "accueil-atelier": ["las-cases", "medium-atelier", "marquise-st-honore"],
  "accueil-metiers": ["perle-apres", "palaiseau", "washington-ensemble", "cloison-acier", "mercier-avant", "bp-vrilliere"],
  "menuiserie-rangee": ["paul-lelong-apres", "vieille-du-temple", "bibliotheque-cheminee"],
  "menuiserie-fin": ["garde-corps-sceaux", "pergola", "bureau-chene", "sous-pente", "grevin", "sas-huissiers"],
  "escaliers-rangee": ["vaucouleurs-avant", "main-courante", "escalier-chene-2017"],
  "escaliers-fin": ["tm-suspendu-2", "tm-suspendu-3", "tm-colimacon-2", "tm-colimacon-3", "tm-limon-1", "tm-autoporteur"],
  "serrurerie-rangee": ["grille-faconnage", "verneuil-lances", "bras-compas"],
  "serrurerie-fin": ["grille-atelier", "grille-motorisee", "boulard", "marquise-st-honore", "motte-modele", "bequille-laiton"],
  "vitrerie-rangee": ["porte-vitree", "pare-douche", "salle-de-bain"],
  "vitrerie-fin": ["marquise-cour", "marquise-lanternes", "palaiseau"],
  "restauration-rangee": ["mercier-cours-1", "conde-greffe", "mercier-detail"],
  "restauration-fin": ["paul-lelong-avant", "paul-lelong-apres", "chauveau-lagarde", "dechargeurs", "abbesses-avant", "abbesses-apres"],
  "belles-rangee": ["bp-messine", "bp-saint-lazare", "bp-lions"],
  "belles-cocheres": ["bp-vrilliere", "bp-richelieu", "bp-bingen", "bp-messine-16", "bp-quai-bourbon", "bp-fbg-montmartre",
    "bp-galilee", "bp-bonaparte-28", "bp-lancry", "bp-bonaparte-74", "bp-chateau-eau-36", "bp-saint-antoine",
    "bp-phalsbourg", "bp-vignon", "bp-thorigny"],
  "belles-autres": ["bp-bourse", "bp-sainte-anne", "bp-tournelles", "bp-sourdiere", "bp-chateau-eau", "bp-amiral"],
  "apropos-rangee": ["las-cases", "bonvin", "saint-paul"],
  "avis-rangee": ["lemoine", "conde-apres", "lappe-apres"],
};

/**
 * Photos des ouvrages et pièces d’archive (src/data/ouvrages.ts) : le nom de
 * fichier y est déjà consigné ; le script les retrouve dans ces dossiers.
 */
export const DOSSIERS_ARCHIVE = [J, G];
